function nl_liacs_dbdm_ftse_ui_FtseModule(){var M='',nb='" for "gwt:onLoadErrorFn"',lb='" for "gwt:onPropertyErrorFn"',Y='"><\/script>',$='#',vb='&',Fb='.cache.html',ab='/',Cb='3E4B43F7C4FE4FFCFDAFD8D49C8E34F3',Ob='<script defer="defer">nl_liacs_dbdm_ftse_ui_FtseModule.onInjectionDone(\'nl.liacs.dbdm.ftse.ui.FtseModule\')<\/script>',X='<script id="',ib='=',_='?',Eb='ABF667C84483FF92D60D68906D2E6D27',kb='Bad handler "',Nb='DOMContentLoaded',Z='SCRIPT',yb='Unexpected exception in locale detection, using default: ',xb='_',wb='__gwt_Locale',W='__gwt_marker_nl.liacs.dbdm.ftse.ui.FtseModule',bb='base',Q='begin',P='bootstrap',db='clear.cache.gif',hb='content',tb='default',Db='en_US',V='end',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',Gb='gwt/chrome/chrome.css',mb='gwt:onLoadErrorFn',jb='gwt:onPropertyErrorFn',gb='gwt:property',Lb='head',Ab='hosted.html?nl_liacs_dbdm_ftse_ui_FtseModule',Kb='href',ob='iframe',cb='img',pb="javascript:''",Hb='link',zb='loadExternalRefs',sb='locale',ub='locale=',eb='meta',rb='moduleRequested',U='moduleStartup',fb='name',N='nl.liacs.dbdm.ftse.ui.FtseModule',qb='position:absolute;width:0;height:0;border:none',Ib='rel',Bb='selectingPermutation',O='startup',Mb='styles.css',Jb='stylesheet';var k=window,l=document,m=k.__gwtStatsEvent?function(a){return k.__gwtStatsEvent(a)}:null,n=k.__gwtStatsSessionId?k.__gwtStatsSessionId:null,o,p,q,r=M,s={},t=[],u=[],v=[],w,x;m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Q});if(!k.__gwt_stylesLoaded){k.__gwt_stylesLoaded={}}if(!k.__gwt_scriptsLoaded){k.__gwt_scriptsLoaded={}}function y(){var b=false;try{var c=k.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||k.external&&k.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}y=function(){return b};return b}
function z(){if(o&&p){var b=l.getElementById(N);var c=b.contentWindow;if(y()){c.__gwt_getProperty=function(a){return F(a)}}nl_liacs_dbdm_ftse_ui_FtseModule=null;c.gwtOnLoad(w,N,r);m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function A(){var e,f=W,g;l.write(X+f+Y);g=l.getElementById(f);e=g&&g.previousSibling;while(e&&e.tagName!=Z){e=e.previousSibling}function h(a){var b=a.lastIndexOf($);if(b==-1){b=a.length}var c=a.indexOf(_);if(c==-1){c=a.length}var d=a.lastIndexOf(ab,Math.min(c,b));return d>=0?a.substring(0,d+1):M}
;if(e&&e.src){r=h(e.src)}if(r==M){var i=l.getElementsByTagName(bb);if(i.length>0){r=i[i.length-1].href}else{r=h(l.location.href)}}else if(r.match(/^\w+:\/\//)){}else{var j=l.createElement(cb);j.src=r+db;r=h(j.src)}if(g){g.parentNode.removeChild(g)}}
function B(){var b=document.getElementsByTagName(eb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(fb),g;if(f){if(f==gb){g=e.getAttribute(hb);if(g){var h,i=g.indexOf(ib);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=M}s[f]=h}}else if(f==jb){g=e.getAttribute(hb);if(g){try{x=eval(g)}catch(a){alert(kb+g+lb)}}}else if(f==mb){g=e.getAttribute(hb);if(g){try{w=eval(g)}catch(a){alert(kb+g+nb)}}}}}}
function C(a,b){return b in t[a]}
function D(a){var b=s[a];return b==null?null:b}
function E(a,b){var c=v;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function F(a){var b=u[a](),c=t[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(x){x(a,d,b)}throw null}
var G;function H(){if(!G){G=true;var a=l.createElement(ob);a.src=pb;a.id=N;a.style.cssText=qb;a.tabIndex=-1;l.body.appendChild(a);m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:rb});a.contentWindow.location.replace(r+J)}}
u[sb]=function(){try{var b;var c=tb||tb;if(b==null){var d=location.search;var e=d.indexOf(ub);if(e>=0){var f=d.substring(e);var g=f.indexOf(ib)+1;var h=f.indexOf(vb);if(h==-1){h=f.length}b=f.substring(g,h)}}if(b==null){b=D(sb)}if(b==null){b=k[wb]}else{k[wb]=b||c}if(b==null){return c}while(!C(sb,b)){var i=b.lastIndexOf(xb);if(i==-1){b=c;break}else{b=b.substring(0,i)}}return b}catch(a){alert(yb+a);return tb}};t[sb]={'default':0,en_US:1};nl_liacs_dbdm_ftse_ui_FtseModule.onScriptLoad=function(){if(G){p=true;z()}};nl_liacs_dbdm_ftse_ui_FtseModule.onInjectionDone=function(){o=true;m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:zb,millis:(new Date).getTime(),type:V});z()};A();var I;var J;if(y()){if(k.external&&(k.external.initModule&&k.external.initModule(N))){k.location.reload();return}J=Ab;I=M}B();m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Bb});if(!y()){try{E([tb],Cb);E([Db],Eb);I=v[F(sb)];J=I+Fb}catch(a){return}}var K;function L(){if(!q){q=true;if(!__gwt_stylesLoaded[Gb]){var a=l.createElement(Hb);__gwt_stylesLoaded[Gb]=a;a.setAttribute(Ib,Jb);a.setAttribute(Kb,r+Gb);l.getElementsByTagName(Lb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Mb]){var a=l.createElement(Hb);__gwt_stylesLoaded[Mb]=a;a.setAttribute(Ib,Jb);a.setAttribute(Kb,r+Mb);l.getElementsByTagName(Lb)[0].appendChild(a)}z();if(l.removeEventListener){l.removeEventListener(Nb,L,false)}if(K){clearInterval(K)}}}
if(l.addEventListener){l.addEventListener(Nb,function(){H();L()},false)}var K=setInterval(function(){if(/loaded|complete/.test(l.readyState)){H();L()}},50);m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:V});m&&m({moduleName:N,sessionId:n,subSystem:O,evtGroup:zb,millis:(new Date).getTime(),type:Q});l.write(Ob)}
nl_liacs_dbdm_ftse_ui_FtseModule();